"""Add role to user

Revision ID: 397cd9fb1805
Revises: 85ec2e931d83
Create Date: 2025-07-01 20:29:58.878872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397cd9fb1805'
down_revision: Union[str, None] = '85ec2e931d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_members')
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_members_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='project_members_user_id_fkey')
    )
    # ### end Alembic commands ###
