"""Add owners and members to project

Revision ID: 6b3494e011d1
Revises: 5bcfbcdef272
Create Date: 2025-07-02 15:27:46.157979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3494e011d1'
down_revision: Union[str, None] = '5bcfbcdef272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owners', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('members', sa.String(), nullable=True))
    op.drop_column('projects', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'members')
    op.drop_column('projects', 'owners')
    # ### end Alembic commands ###
